name: "TF2C Build"
on: push

jobs:
  export-windows:
    name: Windows Export
    runs-on: windows-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          pip install zstd rich httpx tqdm pyinstaller python-gettext
      - name: Do localisations
        run: |
          ./GenerateMO.sh
        shell: bash
      - name: Build Windows
        run: |
          .\CompileWindows
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: dist/tf2c_downloader.exe
  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          pip install zstd rich httpx tqdm pyinstaller python-gettext
      - name: Build Linux
        run: |
          ./GenerateMO.sh
          ./CompileLinux.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: dist/tf2c_downloader
          
